# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
pod 'IQKeyboardManagerSwift'
pod 'Alamofire', '4.8.1'
pod 'MBProgressHUD'
pod 'Kingfisher'
pod 'TDWebServiceAlamofire','4.8.1.1'
pod 'ReachabilitySwift'
pod 'ObjectMapper', '~> 3.5.1'
pod 'KeychainSwift', '~> 16.0.1'
pod 'GooglePlaces'
pod 'GoogleSignIn'

end
